target-version = "py311"
force-exclude = true
extend-exclude = [
    "*chat_templates.py",
    "*ollama_template_mappers.py",
    "*_auto_install.py",
    "*mapper.py",
]

[lint]
select = ["E9", "F63", "F7", "F82"]
ignore = [
    "E402",
    "E722",
    "F403",
    "F405",
    "F811",
    "F821",
    "F841",
    "F401",
    "E731",
    "E741",
    "F601",
    "E712",
]

[format]
